version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["angular"]
  module_system = "es-modules"
  environment = [
    "mongo",
    "jest",
    "nodejs"
  ]
  dialect = "typescript"
